#!/bin/bash
###############################################################################
# The purpose of this file is to create or touch a file periodically so that
# when the code syncs github, it will trigger a build.
###############################################################################

cd /root/gitrepos/docker_pipeline

date >  file_just_for_code_change_trigger

git add . ; git commit -am "new changes as of `date`" ; git push

